CREATE DATABASE IF NOT EXISTS `butouha_app`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `butouha_app`;

CREATE TABLE IF NOT EXISTS `posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `pdf_path` VARCHAR(255) DEFAULT NULL,
  `audio_path` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
